### ISSUE TITLE
unable to build docs

### ISSUE THREAD

**Issue by saifikhan** [RalfJung/rust-101#23]
installed pycco
```
git clone git://github.com/pycco-docs/pycco.git
cd pycco
sudo python setup.py install
```
cd samples/rust-101
an attempt to build docs leads to the following error
```
$ make docs
src/part12.rs -> .tmp/docs/part12.rs
Traceback (most recent call last):
  File "./pycco-rs", line 48, in <module>
    pycco.main.main()
  File "/usr/lib/python3.6/site-packages/Pycco-0.5.1-py3.6.egg/pycco/main.py", line 619, in main
  File "/usr/lib/python3.6/site-packages/Pycco-0.5.1-py3.6.egg/pycco/main.py", line 532, in process
  File "/usr/lib/python3.6/site-packages/Pycco-0.5.1-py3.6.egg/pycco/main.py", line 520, in next_file
  File "./pycco-rs", line 36, in generate_documentation
    '<link rel="stylesheet" href="pycco_custom.css"><meta name="viewport" content="width=device-width">')
  File "./pycco-rs", line 10, in patch_html
    assert source.count(marker) == 1
TypeError: a bytes-like object is required, not 'str'
make: *** [Makefile:19: docs/part12.html] Error 1
rm .tmp/docs/part12.rs
```

**Comment by RalfJung** [comment]
I just tried latest pycco (via `pip install pycco --user`) and things work just fine here.

Could it be that you are using Python 3? "bytes-like object" makes it sound like that. Which distribution are you on? What does `/usr/bin/python --version` say?

**Comment by chinanf-boy** [comment]
@RalfJung 

**I Fix the docs build : python2.7**

## 2018 10.5 can no build docs

## run `pip install pycco && make docs`

### bug 1

``` bash
  File "./pycco-rs", line 14, in <module>
    pycco.main.languages[".rs"] = { "name": "rust", "symbol": "//"}
AttributeError: module 'pycco.main' has no attribute 'languages'
```

#### Fix: `languages` => `supported_languages`

``` py
pycco.main.languages[".rs"] = { "name": "rust", "symbol": "//"}
for ext, l in pycco.main.languages.items():
// fix
pycco.main.supported_languages[".rs"] = { "name": "rust", "symbol": "//"}
for ext, l in pycco.main.supported_languages.items():
```

#### in case

https://github.com/pycco-docs/pycco/blob/master/pycco/main.py#L61

``` py
from pycco.languages import supported_languages
```

### bug 2

``` bash
  File "./pycco-rs", line 17, in <module>
    l["comment_matcher"] = re.compile(r"^\s*" + l["symbol"] + "\s?")
KeyError: 'symbol'
```

#### Fix: all the `symbol` => `comment_symbol`

``` py
"comment_symbol": "//"}
# ...
l["comment_symbol"]
```

#### in case

https://github.com/pycco-docs/pycco/blob/master/pycco/main.py#L353

``` py
def compile_language(l):
    """
    Build out the appropriate matchers and delimiters for each language.
    """
    language_name = l["name"]
    comment_symbol = l["comment_symbol"] # <==== api changed

```

**Comment by RalfJung** [comment]
Fixed by https://github.com/RalfJung/rust-101/pull/31
